server:
  port: 5000

spring:
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 1800000 #30min
      idle-timeout: 600000 #10min
  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.


file:
  dir: ${fileDir}


jwt:
  expiration_time: 86400000 #1일
  secret: ${jwtSecret}