server:
  port: 4000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-manage
          predicates:
            - Path=/api/account/**
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay
          metadata:
            requiredScope: account-manage.access

        - id: user-service
          uri: lb://user-manage
          predicates:
            - Path=/api/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay
          metadata:
            requiredScope: user-manage.access

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *  # CORS ??
  r2dbc:
    url: ${url}
    username: ${username}
    password: ${password}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
#  datasource:
#    url: ${url}
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${username}
#    password: ${password}
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 5
#      max-lifetime: 1800000 #30min
#      idle-timeout: 600000 #10min
  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.


file:
  dir: ${fileDir}


jwt:
  expiration_time: 86400000 #1?
  secret: ${jwtSecret}